name: Build and Push Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build_job:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout of branch ${{ github.ref_name }}
        uses: actions/checkout@v4

      # Set up Docker Buildx (optional but recommended for advanced Docker builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry using GitHub Actions secrets
      - name: Log in to GitHub Container Registry
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.ARMA_CI_PACKAGE_RW }}

      # Build the Docker image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag arma:latest

      # Tag the Docker image for GitHub Container Registry
      - name: Tag the Docker image
        run: docker tag arma:latest ghcr.io/aureprod/arma:latest

      # Push the Docker image to GitHub Container Registry
      - name: Push the Docker image
        run: docker push ghcr.io/aureprod/arma_3_server_docker:latest
